const LIST_LIMIT_PERPAGE = [10, 25, 50, 100]
const LIMIT_PERPAGE_DEFAULT = LIST_LIMIT_PERPAGE[0]
const SORT_DIRECTION = ['asc', 'desc']
const DEFAULT_PAGE = 1
const DEFAULT_LIMIT = 10

export { LIST_LIMIT_PERPAGE, LIMIT_PERPAGE_DEFAULT, SORT_DIRECTION, DEFAULT_PAGE, DEFAULT_LIMIT }
